[package]
name = "rum"
version = "0.1.0"
edition = "2021"
author = "Yann Youbi <yann-ybi@uri.edu>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.release]
lto = true
debug = true
